# Generated by Django 5.2.1 on 2025-05-30 06:34

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('فوتبال', 'فوتبال'), ('والیبال', 'والیبال'), ('بسکتبال', 'بسکتبال')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('icon', models.FileField(upload_to='sport_icons/', verbose_name='آیکون ورزش')),
            ],
            options={
                'verbose_name': 'ورزش',
                'verbose_name_plural': 'ورزش\u200cها',
            },
        ),
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='محتوا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'قوانین و مقررات',
                'verbose_name_plural': 'قوانین و مقررات',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255, unique=True, verbose_name='شناسه تراکنش')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ (دلار)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('verified', 'تایید شده'), ('rejected', 'رد شده'), ('expired', 'منقضی شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='امتیاز')),
                ('has_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='موجودی (دلار)')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='درباره من')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='موقعیت')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('referral_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد دعوت')),
                ('referral_points', models.IntegerField(default=0, verbose_name='امتیاز دعوت')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='football.profile', verbose_name='دعوت شده توسط')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تیم')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/', verbose_name='لوگو')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True, verbose_name='نماد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('sport', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='football.sport', verbose_name='ورزش')),
            ],
            options={
                'verbose_name': 'تیم',
                'verbose_name_plural': 'تیم\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='تاریخ مسابقه')),
                ('home_team_score', models.IntegerField(blank=True, null=True, verbose_name='امتیاز واقعی تیم میزبان')),
                ('away_team_score', models.IntegerField(blank=True, null=True, verbose_name='امتیاز واقعی تیم مهمان')),
                ('venue', models.CharField(max_length=200, verbose_name='محل برگزاری')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_finished', models.BooleanField(default=False, verbose_name='پایان یافته')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='football.sport', verbose_name='ورزش')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='football.team', verbose_name='تیم مهمان')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='football.team', verbose_name='تیم میزبان')),
            ],
            options={
                'verbose_name': 'مسابقه',
                'verbose_name_plural': 'مسابقات',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wallet_address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست برداشت',
                'verbose_name_plural': 'درخواست\u200cهای برداشت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='پیش\u200cبینی امتیاز تیم میزبان')),
                ('away_team_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='پیش\u200cبینی امتیاز تیم مهمان')),
                ('is_correct', models.BooleanField(default=False, verbose_name='صحیح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='football.match', verbose_name='مسابقه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیش\u200cبینی',
                'verbose_name_plural': 'پیش\u200cبینی\u200cها',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'match')},
            },
        ),
        migrations.CreateModel(
            name='UserSportPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_prediction', models.DateTimeField(auto_now_add=True)),
                ('is_selected_for_today', models.BooleanField(default=False)),
                ('has_paid', models.BooleanField(default=False)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.sport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیش\u200cبینی ورزشی کاربر',
                'verbose_name_plural': 'پیش\u200cبینی\u200cهای ورزشی کاربران',
                'unique_together': {('user', 'sport')},
            },
        ),
    ]
