# Generated by Django 5.2.1 on 2025-05-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='network',
            field=models.CharField(choices=[('trc20', 'USDT (TRC20)'), ('bep20', 'BNB (BEP20)')], default='trc20', max_length=20, verbose_name='شبکه'),
        ),
    ]
