# Generated by Django 5.2.1 on 2025-05-21 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date'], 'verbose_name': 'مسابقه', 'verbose_name_plural': 'مسابقات'},
        ),
        migrations.AddField(
            model_name='match',
            name='sport',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='football.sport', verbose_name='ورزش'),
            preserve_default=False,
        ),
    ]
