# Generated by Django 5.2.1 on 2025-06-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_payment_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersportprediction',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
