# Generated by Django 5.2.1 on 2025-06-26 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_usersportprediction_payment_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSportPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.sport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پرداخت ورزشی کاربر',
                'verbose_name_plural': 'پرداخت\u200cهای ورزشی کاربران',
                'unique_together': {('user', 'sport', 'payment_date')},
            },
        ),
    ]
