# Generated by Django 5.2.1 on 2025-06-28 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_usersportpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersportpayment',
            name='payment_window_start',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
