# Generated by Django 5.2.1 on 2025-07-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_usersportpayment_payment_window_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='network',
            field=models.CharField(choices=[('trc20', 'USDT (TRC20)'), ('bep20', 'BNB (BEP20)'), ('btc', 'Bitcoin (BTC)'), ('doge', 'Dogecoin (DOGE)'), ('trx', 'Tron (TRX)'), ('ada', 'Cardano (ADA)'), ('ton', 'TON (TON)')], default='trc20', max_length=20, verbose_name='شبکه'),
        ),
    ]
